language: c++

compiler:
    - clang
    - gcc

dist: trusty
sudo: require

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libboost-all-dev
            - cmake

before_script:
    - mkdir release
    - cd release
    - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ../

script:
    - make
    - test_dist/diff.sh

notifications:
    email: false
