SET(MINGW32_NAME i486-mingw32)

SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_SYSTEM_PROCESSOR x86)
 
SET(CMAKE_C_COMPILER   "${MINGW32_NAME}-gcc")
SET(CMAKE_CXX_COMPILER "${MINGW32_NAME}-c++")
SET(CMAKE_RC_COMPILER  "${MINGW32_NAME}-windres")
 
SET(CMAKE_FIND_ROOT_PATH "/usr/${MINGW32_NAME}" "/usr/local/${MINGW32_NAME}")
 
# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
